services:
  redis:
    image: 'redis:latest'
    healthcheck:
      test: redis-cli info persistence | grep "^loading:0"
      interval: 5s
      retries: 10
    ports:
      - '6379'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'